### ISSUE TITLE
cloning issue

### ISSUE THREAD

**Issue by shrishty19** [ebanigogia/dollar_bot#1]
error: invalid path 'docs/dollar_bot/**/*.html'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by ebanigogia** [comment]
Try cloning the repository without immediately checking out working tree: git clone <repo-url> --no-checkout
