### ISSUE TITLE
multiple running instances 

### ISSUE THREAD

**Issue by shrishty19** [ebanigogia/dollar_bot#6]
i am getting this error :
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request

i understand this is because of multiple instances of the bot are running

**Comment by rhythmjagota** [comment]
I am getting the same issue.

**Comment by ebanigogia** [comment]
Please give some time between shutting down and starting new instances.

**Comment by shrishty19** [comment]
its working for me now

**Comment by rhythmjagota** [comment]
Its working for me as well.
