### ISSUE TITLE
Getting an error of bot not found on line 38 of code_deletion.py file.

### ISSUE THREAD

**Issue by rhythmjagota** [ebanigogia/dollar_bot#7]
I am getting an error of bot not found on line 38 of code_deletion.py file. I have passed bot as a parameter in confirm_deletion function as well but still giving error.

**Comment by shrishty19** [comment]
try passing the bot where you are calling the function confirm deletion

**Comment by rhythmjagota** [comment]
I have added but still getting the error.

**Comment by shrishty19** [comment]
at what position have you added the bot in the confirm deletion function?

**Comment by rhythmjagota** [comment]
At the 2nd place before calling confirm_deletion

**Comment by shrishty19** [comment]
try calling at 3rd position

**Comment by rhythmjagota** [comment]
Yes, now it is not giving error and is working fine. Thanks.

**Comment by shrishty19** [comment]
great!
